export const TYPE_IMAGES = {
  normal: require("@/assets/images/pokemon-types/normal.png"),
  fire: require("@/assets/images/pokemon-types/fire.png"),
  water: require("@/assets/images/pokemon-types/water.png"),
  electric: require("@/assets/images/pokemon-types/electric.png"),
  grass: require("@/assets/images/pokemon-types/grass.png"),
  ice: require("@/assets/images/pokemon-types/ice.png"),
  fighting: require("@/assets/images/pokemon-types/fighting.png"),
  poison: require("@/assets/images/pokemon-types/poison.png"),
  ground: require("@/assets/images/pokemon-types/ground.png"),
  flying: require("@/assets/images/pokemon-types/flying.png"),
  psychic: require("@/assets/images/pokemon-types/psychic.png"),
  bug: require("@/assets/images/pokemon-types/bug.png"),
  rock: require("@/assets/images/pokemon-types/rock.png"),
  ghost: require("@/assets/images/pokemon-types/ghost.png"),
  dragon: require("@/assets/images/pokemon-types/dragon.png"),
  dark: require("@/assets/images/pokemon-types/dark.png"),
  steel: require("@/assets/images/pokemon-types/steel.png"),
  fairy: require("@/assets/images/pokemon-types/fairy.png"),
  stellar: require("@/assets/images/pokemon-types/stellar.png"),
  unknown: require("@/assets/images/pokemon-types/unknown.png"),
  shadow: require("@/assets/images/pokemon-types/shadow.png"),
};
